# Generated by Django 5.0.3 on 2024-03-09 02:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogpost_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
