# Generated by Django 5.0.3 on 2024-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blogpost_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="1", max_length=100),
        ),
    ]
