# Generated by Django 5.0.3 on 2024-03-10 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_blogpost_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="author",
        ),
    ]
