# Generated by Django 5.0.3 on 2024-03-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_blogpost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
