# Generated by Django 5.0.3 on 2024-03-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_blogpost_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
