# Generated by Django 5.0.3 on 2024-03-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_blogsubcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogsubcomment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcomments",
                to="blog.blogcomment",
            ),
        ),
    ]
