# Generated by Django 5.0.3 on 2024-03-14 00:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("decks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deckpost",
            old_name="deck_img",
            new_name="deck_list",
        ),
    ]
